<!-- 
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_AjaxCartPro
 * @version     1.1
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
-->

<div id="ajaxcustomblock" style="display:block;">
    <script type="text/javascript">
        var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    </script>
    <?php
    $de = json_decode($this->getJsonConfig());
    $_product = $this->getProduct() ?>
    <form id="product_addtocart_form" <?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <input type="hidden" value="<?php echo $de->productId ?>" name="product">
        <?php echo $this->getChildHtml('product_js');?>
        <div id="">
            <div class="productoptions"  style="margin:0">
                <div class="productname"><?php echo $_product->getName() ?></div>
                <?php echo $this->getChildHtml('product_options');?>
                <?php echo $this->getChildHtml('product_configurable_options');?>
                <?php echo $this->getChildHtml('product_price');?>
                <div style="margin:0px auto;">
                    <a href="javascript:ajaxClose('custom-option');" >
                        <?php echo $this->__('Continue Shopping')?>
                    </a>
                   <a href="#" id="" class="" onclick="return addcart('<?php echo  Mage::app()->getFrontController()->getRequest()->getParam('wish'); ?>')" style="float:right;">
                        <?php echo $this->__('Add to cart')?>
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>
